export enum LocalizationMessage {
  INTERNAL_SERVER_ERROR = 'common.INTERNAL_SERVER_ERROR',
  VALIDATE_OBJECT_ID = 'common.VALIDATE.OBJECT_ID',
  GET_PAGINATION_SUCCESSFULLY = 'common.GET_PAGINATION_SUCCESSFULLY',
  TOO_MANY_REQUEST_ERROR = 'common.TOO_MANY_REQUEST_ERROR',
  USER_BANNED_ERROR = 'common.USER_BANNED_ERROR',
  REDIS_SERVICE_DOWN = 'common.REDIS_SERVICE_DOWN',
  USER_NOT_FOUND = 'user.USER_NOT_FOUND',
  GET_USER_PROFILE_SUCCESSFULLY = 'user.GET_USER_PROFILE_SUCCESSFULLY',
}
